telegram_token: "token goes here"

# templates definitions
# default template used for all chats by default
templates:
  default:
    |
    <b>{{ .Annotations.message }}</b>
    <code>{{ .Labels.alertname }}</code> [ {{ .Labels.k8s }} / {{ .Labels.severity }} ]

# assign template for specific chat
# (default template will be used for all other cases)
chats_templates:
  # "chatID": custom_template_name
